 AWSTemplateFormatVersion: 2010-09-09
 Description: > 
   This template creates an EC2 instance and a security group with
   inbound port 3000, 22 open to the public  
 Resources:
   EC2Instance:
     Type: 'AWS::EC2::Instance'
     Properties:
       SecurityGroups:
         - !Ref InstanceSecurityGroup     
       KeyName: cd_key
       ImageId: 'ami-0fc5d935ebf8bc3bc' 
       InstanceType: t3.micro
   InstanceSecurityGroup:
     Type: 'AWS::EC2::SecurityGroup'
     Properties:
       GroupDescription: Enable SSH access via port 22
       SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: '22'
           ToPort: '22'
           CidrIp: 0.0.0.0/0
