version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create cloudformation stack"
          command: |
            aws cloudformation deploy \
            --template-file file://infra-template.yml \
            --stack-name infra-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1

workflows:
  infrastructure-workflow:
    jobs:
      - create-infrastructure
