---
- name: "update apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "upgrade all packages on servers"
  become: true
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer require"
  become: true
  apt:
    autoremove: yes

- name: "install nodejs and npm dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "creates directory"
  file:
    path: ~/web
    state: directory

- name: "copy index test page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "Executing node"
  become: true
  shell: |
    pm2 start ~/web/index.js -f
